#!/usr/bin/env bash

# Copyright (c) 2021 Genome Research Ltd.
#
# Authors:
# * Guillaume Noell <gn5@sanger.ac.uk>
# * Christopher Harrison <ch12@sanger.ac.uk>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

get_job_id() {
  local job_name="$1"

  bjobs -J "${job_name}" -noheader -o JOBID 2>/dev/null \
  | awk '
    NR == 1 { job_id = $0 }

    END {
      switch (NR) {
        case 1:
          print job_id
          break

        case 0:
          print "No RStudio Server jobs found" > "/dev/stderr"
          exit 1
          break

        default:
          print "Multiple RStudio Server jobs found" > "/dev/stderr"
          exit 1
          break
      }
    }
  '
}

declare JOB_NAME="bsub rstudio user $(whoami)"
declare JOB_ID

if JOB_ID="$(get_job_id "${JOB_NAME}")"; then
  echo "RStudio Server running as job ${JOB_ID}" >&2
  [[ "${NO_KILL+x}" ]] || bkill "${JOB_ID}"
fi
